<?php

namespace HackTheHub\Leaves\Event;

use HackTheHub\Models\Event\Event;
use Rhubarb\Leaf\Controls\Common\Buttons\Button;
use Rhubarb\Leaf\Views\View;

class EventCollectionView extends View
{
    public function createSubLeaves()
    {
        parent::createSubLeaves(); // TODO: Change the autogenerated stub
    }
    
    protected function printViewContent()
    {
        print "<style>@import 'https://fonts.googleapis.com/css?family=Roboto:300,400,500';

body{
    margin: 0px;
    padding:0px;
    font-family: Roboto;
    font-weight: 400;
    color: white;
    font-size: 18px;
    background-color: #3498db;
}
</style>";

        print "<center>";
        print "<a href='add/'>Want to add your own event? click here!</a><br><br>";
        $events = Event::find();
        foreach ($events as $event){
            print $event->Name . "<br>";
            print $event->DateTimeStart . "<br>";
            print "£".$event->Cost . "<br>";
            print "<a href='$event->TicketLink'>Get tickets or sign up</a>" . "<br><br>";
        }
        print "</center>";
    }
}