<?php

namespace HackTheHub\Leaves\Event;

use Rhubarb\Leaf\Controls\Common\Buttons\Button;
use Rhubarb\Leaf\Views\View;

class EventCollectionView extends View
{
    public function createSubLeaves()
    {
        parent::createSubLeaves(); // TODO: Change the autogenerated stub
    }
    
    protected function printViewContent()
    {
        print "Event collection <br> <a href='add/'>Add an Event: </a>";
    }
}